services:
  - type: web
    name: threatlens-ai
    env: docker
    region: ohio
    plan: starter # You can change this to free if applicable
    branch: main
    envVars:
      - key: PORT
        value: 4001
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
